config/routes.rb
Rails.application.routes.draw do


  # 会員側
  devise_for :users, controllers:{
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  
  # 会員側
  scope module: :public do
    root to: 'homes#top'
    get "/about" => "homes#about", as: "about"
    
    # ユーザー
    resources :users, only:[:index, :show, :edit, :update] do
      member do
        get :favorites
        get :posts
        get :group_post
        get :groups
        get :confirm
        patch :withdraw
      end
    end
    # 投稿
    resources :posts do
      collection do
        get '/search_index' => "posts#search_index", as: "search_index"
      end
      resource :favorites, only:[:create, :destroy]
      resources :comments, only:[:create, :destroy]
    end
    # グループ
    resources :groups do
      #グループ内投稿画面
      get '/post_index' => "groups#post_index" , as: "post_index"
      #グループ作成者がメンバーを追加するためのユーザーリスト
      get '/join_group' => "groups#join_group", as: "join_group"
      #グループにメンバーの追加
      post '/join_user' => "groups#join_user", as: "join_user"
      #グループのメンバーの削除
      delete '/join_destroy' => "groups#join_destroy", as: "join_destroy"
      #グループの削除
      delete "all_destroy" => 'groups#all_destroy'
    end

  end

 # 管理者側
  devise_for :admin, controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }
  
  namespace :admin do
    # ユーザー
    resources :users, only:[:index, :show, :edit, :update, :destroy] do
      member do
        get :posts
        get :groups
        get :group_post
      end
    end
    # 投稿
    resources :posts, only:[:index, :show, :destroy, :edit, :update] do
      # コメント
      resources :comments, only:[:destroy]
    end
    # コメント一覧
    resources :comments, only:[:index]
    # グループ
    resources :groups, only:[:index, :show] do
      # グループ内投稿
      get '/post_index' => "groups#post_index" , as: "post_index"
      # グループの削除
      delete "all_destroy" => 'groups#all_destroy'
    end
    
    
  end
  
  
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :group_image
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, dependent: :destroy
  has_many :posts, dependent: :destroy
  belongs_to :owner, class_name: 'User', foreign_key: :owner_id

  validates :name, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 500 }
  
  #グループイメージの画像
  def get_group_image(width, height)
    unless group_image.attached?
      file_path = Rails.root.join('app/assets/images/no_group_image.jpg')
      group_image.attach(io:File.open(file_path),filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    group_image.variant(resize_to_limit:[width, height]).processed
  end
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController
  before_action :authenticate_admin!
    
    
  def show
    @group = Group.find(params[:id])
  end
  
  def post_index
    @group = Group.find(params[:group_id])
    @posts = @group.posts
  end
  
  
  private

  # フォームから渡す必要がないためowner_idはparamsに入れる必要がない
  def group_params
    params.require(:group).permit(:name, :content, :group_image)
  end
  
  
  
  
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/views/admin/groups/post_index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h3 class="border-bottom">作品集</h3>
    </div>
     <div class="col-sm-12 m-2 d-flex flex-wrap">
      <% @posts.each do |post| %>
        <div class="card m-1 shadow-sm" style="width: 13rem;">
          <div class="review-img card-img-top">
          <%= link_to admin_post_path(post.id) do %>
            <%= image_tag post.images[0].variant(resize: '200x200') %>
          <% end %>
          </div>
          <div class="card-body" style="border-top:solid">
            <div class="d-flex">
              <%= link_to admin_user_path(post.user) do %>
                <%= image_tag post.user.get_profile_image(50,50), class:"rounded" %>
              <% end %>
              <p class="mt-4 pl-2"><%= post.user.nickname %></p>
            </div>
            <h5 class="card-title"><%= post.title %></h5>
            <% if post.is_status == true %>
              <p class="text-success font-width-bold">公開</p>
            <% else %>
              <p class="text-secondary font-width-bold">非公開</p>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/groups/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h3><%= @group.name %></h3>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>メンバー</th>
            <th>グループ内容</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= image_tag @group.get_group_image(200,200), class: "rounded image_group" %></td>
            <td>
              <% @group.users.each do |user| %>
                <%= user.nickname %><br>
              <% end %>
            </td>
            <td class="col-sm-5"><%= @group.content %></td>
            <td>
                <%= link_to "グループ作品集", admin_group_post_index_path(@group.id), class:'btn btn-picture' %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>