config/routes.rb
Rails.application.routes.draw do


  # 会員側
  devise_for :users, controllers:{
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  
  # 会員側
  scope module: :public do
    root to: 'homes#top'
    get "/about" => "homes#about", as: "about"
    
    # ユーザー
    resources :users, only:[:index, :show, :edit, :update] do
      member do
        get :favorites
        get :posts
        get :group_post
        get :groups
        get :confirm
        patch :withdraw
      end
    end
    # 投稿
    resources :posts do
      collection do
        get '/search_index' => "posts#search_index", as: "search_index"
      end
      resource :favorites, only:[:create, :destroy]
      resources :comments, only:[:create, :destroy]
    end
    # グループ
    resources :groups do
      #グループ内投稿画面
      get '/post_index' => "groups#post_index" , as: "post_index"
      #グループ作成者がメンバーを追加するためのユーザーリスト
      get '/join_group' => "groups#join_group", as: "join_group"
      #グループにメンバーの追加
      post '/join_user' => "groups#join_user", as: "join_user"
      #グループのメンバーの削除
      delete '/join_destroy' => "groups#join_destroy", as: "join_destroy"
      #グループの削除
      delete "all_destroy" => 'groups#all_destroy'
    end

  end

 # 管理者側
  devise_for :admin, controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }
  
  namespace :admin do
    # ユーザー
    resources :users, only:[:index, :show, :edit, :update, :destroy] do
      member do
        get :posts
        get :groups
        get :group_post
      end
    end
    # 投稿
    resources :posts, only:[:index, :show, :destroy, :edit, :update] do
      # コメント
      resources :comments, only:[:destroy]
    end
    # コメント一覧
    resources :comments, only:[:index]
    # グループ
    resources :groups, only:[:index, :show] do
      # グループ内投稿
      get '/post_index' => "groups#post_index" , as: "post_index"
      # グループの削除
      delete "all_destroy" => 'groups#all_destroy'
    end
    
    
  end
  
  
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, :source => :post
  has_many :comments, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :group_members, through: :group_users, :source => :group
  has_many :my_groups, through: :group_users, dependent: :destroy
  has_many :groups, foreign_key: :owner_id

  validates :nickname, presence: true, length: { in: 2..20 }
  validates :introduction, length: {maximum: 300 }
  validates :email, uniqueness: true

  #ゲストログイン
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.nickname = "ゲストユーザー"
    end
    redirect_to root_path
  end

  #プロフィール画像設定
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io:File.open(file_path),filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit:[width, height]).processed
  end

  #マイページ(show)使用
  def me?(user_id)
    id == user_id
  end

  #検索フォーム
  def self.search(method,word)
    if method == "partial_match"
      @users = User.where("nickname LIKE ?", "%#{word}%").where(is_active: true)
    elsif method == "perfect_match"
      @users = User.where(nickname: word).where(is_active: true)
    else
      @users = User.where(is_active: true)
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    if params[:search].present? && params[:word].present?
      #Userモデルファイルにsearchとwordを定義
      @users = User.search(params[:search], params[:word]).page(params[:page]).per(10)
    else
      @users = User.page(params[:page])
    end
  end
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.where(post_type: 0).recent
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to admin_user_path(user.id)
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end
  
  def posts
    @user = User.find(params[:id])
    # pluck = 指定したカラム(この場合post_id)のレコードの配列を取得
    @posts = Post.where(user_id: @user.id).pluck(:id)
    # whereを使ってpost_typeを検索して投稿した自分だったら全てを表示する
    @posts = @user.posts.where(post_type: 0).page(params[:page])
  end
  
  def groups
    @user = User.find(params[:id])
    # @groups= GroupUser.where(user_id: @user.id).page(params[:page]).pluck(:group_id)
    # アソシエーションでgroupは持っているためwhereを使わずとも下記の定義でとってこれる
    @groups = @user.groups.page(params[:page])
  end
  
  def group_post
    @user = User.find(params[:id])
    @posts = @user.posts.where(post_type: 1).order('id DESC').page(params[:page])
  end
  
  private
  
  def user_params
    params.require(:user).permit(:nickname, :email, :is_active)
  end
  
  
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-xs-11">
      <h3>プロフィール編集</h3>

      <%= form_with model: @user, url: admin_user_path, method: :patch do |f| %>

        <div class="form-group">
          <%= f.file_field :profile_image, class: "form-control-file", accept: "image/*" %>
        </div>
        <div class="form-group">
          <label for="user_name">ニックネーム</label>
          <%= f.text_field :nickname, class: "form-control name", autofocus: true, id:"user_name" %>
        </div>
        <div class="form-group">
          <label for="user-introduction">自己紹介</label>
          <%= f.text_area :introduction, rows: "6", class: "form-control introduction" %>
        </div>
        <div class="form-group">
          <label for="user-is_active">ユーザーステータス</label>
          <div>
            <%= f.radio_button :is_active, :true %>
            <%= f.label :is_active, "有効", {value: :true, style: "display: inline-block"} %>
            <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, "退会", {value: :false, style: "display: inline-block"} %>
          </div>
        </div>

        <div class="form-group">
          <%= f.submit "変更を保存する", class:"btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/group_post.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 m-3 p-0 d-flex flex-wrap">
    <% @posts.each do |post| %>
      <div class="card m-2 shadow-sm" style="width: 13rem;">
        <div class="review-img card-img-top">
        <%= link_to admin_post_path(post.id) do %>
          <%= image_tag post.images[0].variant(resize: '200x200') %>
        <% end %>
        </div>
        <div class="card-body" style="border-top:solid">
          <%= link_to admin_user_path(post.user) do %>
            <%= image_tag post.user.get_profile_image(50,50), class:"rounded-circle" %>
          <% end %>
          <h5 class="card-title"><%= post.title %></h5>
          <% if post.is_status == true %>
            <p class="text-success font-width-bold">公開</p>
          <% else %>
            <p class="text-secondary font-width-bold">非公開</p>
          <% end %>
        </div>
      </div>
    <% end %>
    </div>
    <div class="mx-auto">
      <%= paginate @posts %>
    </div>
  </div>
</div>

app/views/admin/users/groups.html.erb
<div class="container">
  <div class="row">
    <table class="table table-hover">
      <thead>
        <tr>
          <th></th>
          <th>グループ名</th>
          <th>内容</th>
          <th>メンバー人数</th>
          <th></th>
        </tr>
      </thead>
      <% @groups.each do |group| %>
      <tbody>
        <tr>
          <td><%= image_tag group.get_group_image(100,100), class: "rounded image_group" %></td>
          <td><%= group.name %></td>
          <td><%= group.content.truncate(30) %></td>
          <td><%= group.users.count %></td>
          <td><%= link_to "入室", admin_group_path(group.id), class:'btn btn-success' %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
    <div class="mx-auto">
      <%= paginate @groups %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto m-2">
      <% # 検索フォーム %>
      <%= form_with url: admin_users_path, local: true, method: :get do |form| %>
        <div class="input-group">
          <%= form.text_field :word, placeholder: "キーワード", class:'form-control  input-group-prepend' %>
          <%= form.select :search, options_for_select([["部分一致","partial_match"], ["完全一致","perfect_match"]]) %>
          <span class="input-group-btn input-group-append">
            <%= form.submit "検索", class:'btn btn-primary' %>
          </span>
        </div>
      <% end %>
    </div>
  </div>
    <div class="row">
      <div class="col-sm-12">
        <h3 class="bg-light">ユーザー一覧</h3>
      </div>
    </div>
  <div class="row">
    <div class="col-sm-12 mx-auto">
      <table class="table">
        <thead>
          <tr class="bg-light">
            <th>ユーザID</th>
            <th>ユーザ名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
            <th></th>
          </tr>
        </thead>
        <% @users.each do |user| %>
          <tbody>
            <tr>
              <td><%= user.id %></td>
              <td>
                <%= image_tag user.get_profile_image(50,50), class: "rounded image_circle_admin" %>
                <%= link_to admin_user_path(user.id) do %>
                  <%= user.nickname %>
                <% end %>
              </td>
              <td><%= user.email %></td>
              <% if user.is_active == true %>
                <td class="text-primary font-width-bold">有効</td>
              <% else %>
                <td class="text-secondary font-width-bold">退会</td>
              <% end %>
              <td>
                <% if user.email != "guest@example.com"  %>
                  <%= link_to "削除", admin_user_path(user), class:'btn btn-sm btn-danger', method: :delete, data: {confirm: "削除しますか？"} %>
                <% end %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
      <div class="col-sm-12">
          <% if @users.size == 0 %>
            <p class="text-center">検索結果がありませんでした</p>
          <% end %>
      </div>
    </div>
    <div class="mx-auto">
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/admin/users/posts.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 m-3 p-0 d-flex flex-wrap">
    <% @posts.each do |post| %>
      <div class="card m-2 shadow-sm" style="width: 13rem;">
        <div class="review-img card-img-top">
        <%= link_to admin_post_path(post.id) do %>
          <%= image_tag post.images[0].variant(resize: '200x200') %>
        <% end %>
        </div>
        <div class="card-body" style="border-top:solid">
          <%= link_to admin_user_path(post.user) do %>
            <%= image_tag post.user.get_profile_image(50,50), class:"rounded" %>
          <% end %>
          <h5 class="card-title"><%= post.title %></h5>
          <% post.tags.each do |tag| %>
            <%= link_to tag.tag_name, admin_posts_path(tag_id: tag.id) %>
          <% end %>
          <% if post.is_status == true %>
            <p class="text-success font-width-bold">公開</p>
          <% else %>
            <p class="text-secondary font-width-bold">非公開</p>
          <% end %>
        </div>
      </div>
    <% end %>
    </div>
    <div class="mx-auto">
      <%= paginate @posts %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-2 m-4">
      <%= image_tag @user.get_profile_image(200,200), class:"rounded image_mypage" %>
    </div>
    <div class="col-sm-6 m-4">
      <div class="form-group">
        <p class="h3 font-weight-bold"><%= @user.nickname %></p>
      </div>
      <div class="form-group d-flex">
        <p class="font-width-bol flex-row mr-2">ステータス</p>
          <% if @user.is_active == true %>
            <p class="text-primary font-width-bold">有効</p>
        　<% else %>
        　  <p class="text-secondary font-width-bold">退会</p>
        　<% end %>
      </div>
      <div class="form-group border border-dark rounded p-1">
        <%= @user.introduction %>
      </div>
      <div class="d-flex flex-row">
        <%= link_to "プロフィール編集", edit_admin_user_path(@user.id), class:'btn btn-success btn-sm mx-1' %>
        <%= link_to "グループ一覧", groups_admin_user_path(@user), class:'btn btn-dark btn-sm mx-1' %>
        <%= link_to "グループ内投稿一覧", group_post_admin_user_path(@user), class:'btn btn-info btn-sm mx-1' %>
      </div>
    </div>

    <div class="col-sm-12">
      <div class="d-flex">
        <h2 class="title flex-row">作品一覧</h2>
        <div class="button offset-1 mt-2">
          <%= link_to "作品一覧", posts_admin_user_path(@user), class: "btn btn-info btn-sm" %>
        </div>
      </div>
      <table class="d-flex border-top">
        <% @posts.each do |post| %>
        <tbody class="flex-row">
          <tr>
            <td>
              <%= link_to admin_post_path(post.id) do %>
                <%= image_tag post.images[0].variant(resize: '200x200'), class: "review-img m-2" %>
              <% end %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>