config/routes.rb
Rails.application.routes.draw do


  # 会員側
  devise_for :users, controllers:{
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  
  # 会員側
  scope module: :public do
    root to: 'homes#top'
    get "/about" => "homes#about", as: "about"
    
    # ユーザー
    resources :users, only:[:index, :show, :edit, :update] do
      member do
        get :favorites
        get :posts
        get :group_post
        get :groups
        get :confirm
        patch :withdraw
      end
    end
    # 投稿
    resources :posts do
      collection do
        get '/search_index' => "posts#search_index", as: "search_index"
      end
      resource :favorites, only:[:create, :destroy]
      resources :comments, only:[:create, :destroy]
    end
    # グループ
    resources :groups do
      #グループ内投稿画面
      get '/post_index' => "groups#post_index" , as: "post_index"
      #グループ作成者がメンバーを追加するためのユーザーリスト
      get '/join_group' => "groups#join_group", as: "join_group"
      #グループにメンバーの追加
      post '/join_user' => "groups#join_user", as: "join_user"
      #グループのメンバーの削除
      delete '/join_destroy' => "groups#join_destroy", as: "join_destroy"
      #グループの削除
      delete "all_destroy" => 'groups#all_destroy'
    end

  end

 # 管理者側
  devise_for :admin, controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }
  
  namespace :admin do
    # ユーザー
    resources :users, only:[:index, :show, :edit, :update, :destroy] do
      member do
        get :posts
        get :groups
        get :group_post
      end
    end
    # 投稿
    resources :posts, only:[:index, :show, :destroy, :edit, :update] do
      # コメント
      resources :comments, only:[:destroy]
    end
    # コメント一覧
    resources :comments, only:[:index]
    # グループ
    resources :groups, only:[:index, :show] do
      # グループ内投稿
      get '/post_index' => "groups#post_index" , as: "post_index"
      # グループの削除
      delete "all_destroy" => 'groups#all_destroy'
    end
    
    
  end
  
  
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<!-- エラー -->
<% if resource.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer p-5 mt-2">
    <div class="container">
      <div class="row">
          <div class="col-sm-12">
            <div class="form-group text-center">
              <p>©︎ 2022 oekaki</p>
            </div>
          </div>
      </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<!-- ヘッダー -->
<header>
  <nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand text-light"><%= link_to "お絵描きparty", root_path, class:'font-weight-bold h3 text-light offset-1 title' %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                  aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %> <!-- ユーザーのヘッダー -->
        <% if current_user.email != "guest@example.com"  %>
          <li class="nav-item m-2">
            <%= link_to "作品を投稿する", new_post_path, class:'btn btn-info' %>
          </li>
          <li class="nav-item m-2">
            <%= link_to "マイページ", user_path(current_user.id), class: 'btn btn-info' %>
          </li>
        <% end %>
        <li class="nav-item m-2">
          <%= link_to "検索", search_index_posts_path, class: 'btn btn-info' %>
        </li>
        <li class="nav-item m-2">
          <%= link_to "ユーザー一覧", users_path, class: 'btn btn-info' %>
        </li>
        <li class="nav-item m-2">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn btn-secondary' %>
        </li>
      <% elsif admin_signed_in? %> <!-- 管理者のヘッダー -->
        <li class="nav-item m-2">
          <%= link_to "コメント一覧", admin_comments_path, class: 'btn btn-warning' %>
        </li>
        <li class="nav-item m-2">
          <%= link_to "投稿一覧", admin_posts_path, class: 'btn btn-success' %>
        </li>
        <li class="nav-item m-2">
          <%= link_to "ユーザ一覧", admin_users_path, class: 'btn btn-success' %>
        </li>
        <li class="nav-item m-2">
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'btn btn-secondary' %>
        </li>
        
        <% else %>
        <li class="nav-item m-2">
          <%= link_to "About", about_path, class:'btn btn-Wstning-about' %>
        </li>
        <li class="nav-item m-2">
          <%= link_to "新規登録", new_user_registration_path, class:'btn btn-Wstning-registration' %>
        </li>
        <li class="nav-item m-2">
          <%= link_to "ログイン", new_user_session_path, class:'btn btn-info-login' %>
        </li>
        <li class="nav-item m-2">
          <%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class:'btn btn-gest' %>
        </li>
      <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>お絵描きParty</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%#link rel="stylesheet" href="./css/my-stylesheets.css"%>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <% #NOTE: ポップアップLightbox2 %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>

  </head>

  <body>
    <%= render 'layouts/header' %>
    <% if notice.present? %>
      <div class="alert alert-success">
        <%= notice %>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="alert alert-danger">
        <%= alert %>
      </div>
    <% end %>
    <%= yield %>

    <%= render 'layouts/footer' %>

  </body>

</html>